### ISSUE TITLE
不要ファイルを消す

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#105]
wwa_psave.ts の各関数など、参照されていない変数やファイルを消していく

wwa_psave.tsの関数はどこからも参照されていないファイルなので報告。（おそらくWWA.javaの挙動を真似ようとして諦めたんだと思います）

**Comment by shine-star** [comment]
現在、PLiCy版のバージョンにてwwa_psave.tsを使用中です。
3.3.0をこちらでマージした際に、こちら側でwwa_psave.tsを使用します。

**Comment by matsuyuki-a** [comment]
wwa_psaveが再利用されるようになったため、Closeします。
