### ISSUE TITLE
AudioJSやめる

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#119]
#118 に関連して。(#118 v3.2.0時点では対応不要です)

IE11(IEは11以外考えないことにする)ではaudio要素におけるMP3形式サウンドの再生に対応しており、IE以外の主要ブラウザ最新版(もう少し厳密に書くと、`window.audioContext` もしくは `window.WebKitAudioContext` を定義するブラウザ)の場合はWebAudioを用いるため、現時点でAudioJSは不要となっている。

ので消したい。

（ただし、もし将来OGG Vorbisに対応することになった場合はIEをどうするかのジャッジが必要になりそうだ）

**Comment by enloyable** [comment]
javasprict
https://design-tera.com/blog/archives/2814/
css
https://rafael.adm.br/css_browser_selector/

あんまりにもブラウザがブラウザが言われて頭痛くなってきたので…これのどっちか導入できませんか？cssだったらファイルの内容的にもしかしたらなんとか手伝えるかもしれませんが、javasprictだとファイルの内容的にほぼそちらに丸投げせざるを得ません。

**Comment by enloyable** [comment]
あるいはjplayerでなんとかできません？
http://www.webdesignleaves.com/wp/jquery/582/
firefoxでうまく行かない場合があるみたいなのは痛いけど…
http://dekasu.net/jplayer/

**Comment by enloyable** [comment]
http://phiary.me/webaudio-api-getting-started/#post-h3-id-3_0
webaudioだとこれかなあ…（恐らく既にご存知でしょうが…）

**Comment by enloyable** [comment]
なんかブラウザのどうのこうのに関連してそう（専門的な知識だらけで頭が限界…）
http://mohayonao.hatenablog.com/entry/2012/12/12/103009

**Comment by enloyable** [comment]
多分上のwebaudioのブラウザのどうのこうのに関連してるってことだけは分かる
https://www.g200kg.com/docs/webaudioapichecker/

**Comment by enloyable** [comment]
古い情報だしもう流石に改善されてるとは思うけど念頭には入れとくといいかも
https://github.com/phi-jp/tmlib.js/issues/133

**Comment by enloyable** [comment]
フラッシュは2020年に終了だから辞めたほうがいいですね。

**Comment by enloyable** [comment]
jplayerでfirefoxでうまく行かない可能性の話。mp3とoggが補完関係になってるからどうにか判定で切り替えられないですか

**Comment by enloyable** [comment]
http://www.html5.jp/html5doctor/native-audio-in-the-browser.html
このサイトの「ソースを使う」はjplayerだと参考になりそう…？

**Comment by matsuyuki-a** [comment]
AudioJS系の文言もなくなったことなので、closeします。

**Comment by matsuyuki-a** [comment]
@enloyable ご協力ありがとうございました！
