### ISSUE TITLE
$mapマクロの出現先がゲームオーバー先に移る

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#121]
`$map` マクロを指定したダメージ床でゲームオーバーになると、 `$map` マクロで指定したパーツがゲームオーバー先で配置される場合がある。

## 発生手順
1. ダメージ床となる背景パーツ1を設定。種類は 道 。
    - `$map=2,p,p,1`
    - 指定位置にパーツを出現では 番号1, X座標p, Y座標p, 物体パーツ として設定。
2. 背景パーツ2を設定。種類は 道 。
    - 今回は適当なメッセージを出力するように設定。
3. ダメージ部分となる物体パーツ1を設定。種類は ステータス変化 。
    - 生命力を `-20` に設定 (ゲームオーバーになれれば値は適当で良い)
4. WWA Wingを起動し、生命力が底を付くまで背景パーツ1に踏み続ける。
5. ゲームオーバー先に背景パーツ2が配置される。

## 原因
マクロ文 `$map` と指定位置にパーツを出現で実行順序にズレが発生していると思われる。
(詳細はこの後更新予定。)

## 環境
- OS: Windows 10 64bit
- ブラウザ: Firefox 66.0.4
- WWA Wingのバージョン: v3.1.8

**Comment by matsuyuki-a** [comment]
#129 も重要なのですが、今のコードでマクロの振る舞いを明確化するのは修羅の道なので、一旦暫定の手段で解決しようと思います。

`wwa_main.ts` の `gameover` メソッドで、 `this.execMacroListInNextFrame` を空配列で初期化すれば多分直ります。
割り込みのタイミング次第かもしれないですが、QuickSaveやQuickLoad、リスタートゲームでも同様の問題がありそう。。。
