### ISSUE TITLE
ブラウザの判定の順序再確認

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#127]
ブラウザの判定の順序の再確認

userエージェントで判定する場合、ブラウザの判定の順序はとても重要なので、https://github.com/WWAWing/WWAWing/pull/123#issuecomment-495243866
判定の順序の再確認をお願いします！
残念ながら私enjoyableは再確認できる環境がありません。

**Comment by matsuyuki-a** [comment]
了解です！各ブラウザでためしてみますねー

**Comment by enloyable** [comment]
https://qiita.com/sakuraya/items/33f93e19438d0694a91d
もう一回貼っときます

**Comment by enloyable** [comment]
https://design-tera.com/blog/archives/2814/
一応これも…

**Comment by enloyable** [comment]
https://github.com/WWAWing/WWAWing/blob/de0627dc2e29c6d9d6427ed8dedf17783719e72b/packages/engine/src/wwa_data.ts#L393
おそらくここのline92もedge先なんじゃ…（順序めちゃくちゃ大事だけどそれ故にいじることに抵抗あり…）

**Comment by enloyable** [comment]
先程のline389で、Chrome先になってしまってます…

**Comment by enloyable** [comment]
そもそもブランチエラーでいじれないし、その重要さゆえ私がいじれたとしてもいじらないほうがよさそうですね

**Comment by enloyable** [comment]
ほぼ体力ないし経緯説明端折るけど、ie11判定しないのでしょうか。それとも見えないだけ？

**Comment by matsuyuki-a** [comment]
確かに！

**Comment by enloyable** [comment]
https://github.com/WWAWing/WWAWing/pull/118
もしこれ「だけ」で私の悩んでるサウンド問題が解決するなら、ie11を入れなくても良いけれど…

**Comment by matsuyuki-a** [comment]
IEの判定入れておきますねー

**Comment by enloyable** [comment]
入れたの確認したいです。そしたら閉めますね

**Comment by enloyable** [comment]
入れたらソースをコピーして貼り付けてくれると助かります。やや見にくい環境なので

**Comment by enloyable** [comment]
![924996F2-9881-45F6-96E0-A3F93651D7E1](https://user-images.githubusercontent.com/50323486/58299715-07b48a80-7e1b-11e9-8eee-d5db2be7b9fa.png)
貼っとく

**Comment by matsuyuki-a** [comment]
> 先程のline389で、Chrome先になってしまってます…
> https://github.com/WWAWing/WWAWing/blob/de0627dc2e29c6d9d6427ed8dedf17783719e72b/packages/engine/src/wwa_data.ts#L389

最新では直ってるはず、最新はこちら↓
https://github.com/WWAWing/WWAWing/blob/develop/packages/engine/src/wwa_data.ts#L389

**Comment by matsuyuki-a** [comment]
IE判定追加PRつくりましたー

**Comment by enloyable** [comment]
わかりました、こっちは閉めます。(書くとこ間違えた)
