### ISSUE TITLE
イベント実行フェイズの明確化

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#129]
#99 #121 で挙げられている通り、マクロの実行が次のフレームになる場合がある。
これは、messageQueueの構造上の問題で、キューからメッセージを出したタイミングでマクロが時以降されることが問題なのだが、どのような仕様に倒すかを考えた上で、いったいどのようなタイミングでWWADataの書き換えを行うかを明確にする。

この問題は、WWA Wing XEで大幅にマクロが増えるタイミングを目標に対策を行う。

**Comment by shine-star** [comment]
ゲームパッド使用時、効果音付きのアイテムをショップで連続で購入した際にアイテム数が増えないことがある症状も同様の原因と思われます。

**Comment by matsuyuki-a** [comment]
#505 である程度改善の目処が立ったのでcloseします。
アイテム使用のタイミングがまだわかりにくいが、今後改善したい。
