### ISSUE TITLE
スマホやipadでwwaphenixが使えない件

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#130]
スマホやipadでwwaphenixが使えなくて困ってます。魔法の呪文を、デモンスダンジョンで直接入力すると文字数エラーになりますし、魔法の呪文を入れておいたブックマークをクリックをしても反応しなかったのです…ものすごく泣きたいのでなんとかしてください。
![Screenshot_20190527-101128](https://user-images.githubusercontent.com/50323486/58390253-4476c080-806b-11e9-982b-f49fdb42662c.jpg)

![Screenshot_20190527-102558](https://user-images.githubusercontent.com/50323486/58390222-142f2200-806b-11e9-9b24-1d4c18ec4cf7.jpg)
![Screenshot_20190527-102542](https://user-images.githubusercontent.com/50323486/58390226-1abd9980-806b-11e9-95f6-62094b167edf.jpg)

**Comment by matsuyuki-a** [comment]
冒頭の javascript: が欠けてないか確認願います

**Comment by enloyable** [comment]
私のブックマーク見れば分かるけど欠けてない…あと他のフェニックス必要なwwaでも起こるし。rave ダンジョン。

**Comment by matsuyuki-a** [comment]
ありがとうございます。確認します。

**Comment by enloyable** [comment]
よろしければまつゆきさんとひらりんさんにも今までの経緯をDMしますけど…（流石にここに載せるのはまずい内容ある）

**Comment by enloyable** [comment]
Ipadだとsafariは拒否るしfirefoxはなぜかブックマーク編集不可

**Comment by enloyable** [comment]
![977F91DF-36AB-4B26-A9E5-8A4FB2AD2E40](https://user-images.githubusercontent.com/50323486/58391290-36776e80-8070-11e9-9d8c-6005db349d4a.png)
![903A78FE-335B-4125-9882-1979A79A5E3C](https://user-images.githubusercontent.com/50323486/58391332-6cb4ee00-8070-11e9-8dd3-1ab22580cf37.png)

**Comment by matsuyuki-a** [comment]
Safariについては、WWA Phoenix のページの説明書きにある通り、もともと利用できないです。これは、アドレスバーからのJavaScript実行を禁止するポリシーのため、やむを得なさそうです。

**Comment by enloyable** [comment]
ちょっと引っ掛かるのはこれかな
http://yomahigoto.blogspot.com/2017/10/androidchrome.html?m=1

**Comment by enloyable** [comment]
引っかかるけど、難しくて理解できないです…

**Comment by enloyable** [comment]
上のリンクの説明をヒントに起動することはできたのですが、やや面倒な手順を踏みました…

**Comment by enloyable** [comment]
かなり面倒な手順ですが、起動することはできたので、締めますか？

**Comment by matsuyuki-a** [comment]
おー、ということはPhoenix 本体の問題じゃなさそうですね

ブックマークレットの追加手順について、追記しようと思います。

**Comment by enloyable** [comment]
スマホの方です。ipadはまだ。同じ面倒な手順踏まなきゃだめかな…

**Comment by matsuyuki-a** [comment]
Safari(や、iOSで動くブラウザ)はもともとサポート対象ではないので諦めています

**Comment by enloyable** [comment]
上のやつのリンクの、かなり下の方に書いてあることを、そのurlを必死で探したんです。それを探したら出来ました…が！そのurlが下の方に表示されてしまい（普通の検索結果が上に出てしまう）かなり苦労しました

**Comment by enloyable** [comment]
しかも成功したurlをコピーしようとしてもまたプレイできなくなってしまうし…いちいち探さないといけないのこれ…

**Comment by enloyable** [comment]
![911BFEB2-13CA-4193-8806-E57B78245F19](https://user-images.githubusercontent.com/50323486/58392643-f1563b00-8075-11e9-9e0f-9ef1dbe44223.png)
さっきから探す探すいってるのはこれです

**Comment by enloyable** [comment]
探さず実行する方法があれば良いけど…それは別イシューにします？

**Comment by enloyable** [comment]
とりあえず実行はできるので締めますね。探さず実行する方法については別イシューにします

**Comment by enloyable** [comment]
とりあえず実行はできるので締めますね。探さず実行する方法については別イシューにします

**Comment by enloyable** [comment]
あ、でも大事なこと見落としてた。wwa作成ツールがが3、18でないなら、旧javaで出力のためPhoenix使用になりますが、3.18だとJavasprict出力だからfirefoxの説明が必要かな。今回は3、18でないからPhoenixのこと説明します！？
