### ISSUE TITLE
phenixのスマホでの煩わしさ解消

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#131]
https://github.com/WWAWing/WWAWing/issues/130
最低限wwaphonixが起動することはできるようになったものの、毎回ブックマークレットのurlを探して貼り付けするという（しかも成功したやつをブックマークしても消える）面倒な手順を踏んでいます。なんとかしたいです…。

**Comment by shine-star** [comment]
WWA Phonixは開発・更新終了をしているようでございます。
https://twitter.com/wwa_wing/status/1094266053062868994
https://wwawing.com/wwap/

**Comment by enloyable** [comment]
ブックマークする際、古いWWA専用サイト!
という名前にして、魔法の呪文であるこれをURLに貼り付けることでかなり検索時の負担は減りました。
javascript:var rt="https://wwaphoenix.github.io/";if(0<frames.length){for(var i=0;i<frames.length;i++) {try {if(0<frames[i].document.getElementsByTagName("applet").length){var a=confirm(frames[i].location.href+"\nでappletを検出。移動しますか?(移動後再度実行してください)\n");if(!0===a){location.href=frames[i].location.href;break}}}catch(e){}}}main(window);function main(c){c.wwap_mode=!0;c.external_script_inject_mode=!0;var b=c.document.createElement("link");b.rel="stylesheet";b.href=rt+"/wwa_classic.css";c.document.getElementsByTagName("head")[0].appendChild(b);c=c.document.getElementsByTagName("applet");if(0<c.length)for(b=0;b<c.length;b++)isWWA(c[b])&&replaceApplet(c[b])}function isWWA(c){return"WWA.class"===c.getAttribute("code")||"WWAX.class"===c.getAttribute("code")}function replaceApplet(c){var b=c.parentElement;b.removeChild(c);var d=document.createElement("div");c=getMapDataFileName(c);d.setAttribute("id","wwa-wrapper");d.classList.add("wwa-size-box");d.setAttribute("data-wwa-mapdata",c);d.setAttribute("data-wwa-loader",rt+"wwaload.js");d.setAttribute("data-wwa-classic-mode-enable",true);c=confirm("URLゲートを有効にしますか?\n(フレームでBGMを再生するWWAではキャンセルを選んでください)");d.setAttribute("data-wwa-urlgate-enable",c);x=confirm("アイテムエフェクトを有効にしますか?(アイテムボックスを何かの表示に使っている作品ではキャンセルをお勧めします)");d.setAttribute("data-wwa-item-effect-enable",x);b.insertBefore(d,b.firstChild);b=document.createElement("script");b.src=rt+"audio/audio.min.js";b.charset="UTF-8";document.getElementsByTagName("head")[0].appendChild(b);b=document.createElement("script");b.src=rt+"wwaload.noworker.js";b.setAttribute("id","wwaloader-ex");b.charset="UTF-8";document.getElementsByTagName("head")[0].appendChild(b);b=document.createElement("script");b.src=rt+"wwa.js";b.charset="UTF-8";document.getElementsByTagName("head")[0].appendChild(b)}function getMapDataFileName(c){for(var b=0;b<c.children.length;b++)if("param"===c.children[b].tagName.toLowerCase()){var d=c.children[b].getAttribute("name"),d=d.toLowerCase();if(null!==d&&"parammapname"===d&&(d=c.children[b].getAttribute("value"),null!==d))return d}throw Error("no mapfile detected.");}void 0;

**Comment by matsuyuki-a** [comment]
はい。確かに更新は終了しており、ブックマークレットのスクリプトの中身に手を加えるのは避けたいのですが、簡単なご案内程度ならできると思います。

**Comment by matsuyuki-a** [comment]
(これまでが不親切すぎた)

**Comment by enloyable** [comment]
ブックマーク時大幅に検索の手間が楽になるので、メモだけしておいて閉じますね。開発終了してるけど

**Comment by enloyable** [comment]
ん？なにか続きがありそうなので再び開けましたよ

**Comment by matsuyuki-a** [comment]
なので、配布ページに使い方をもうちょっと親切めに書こうかな〜という感じですね

**Comment by enloyable** [comment]
https://github.com/WWAWing/WWAWing/issues/130#issuecomment-496061019

**Comment by enloyable** [comment]
(ブックマークの名前ね）

**Comment by enloyable** [comment]
ちなみにフェニックスの使い方更新したら載せてください。そしたら閉じます

**Comment by enloyable** [comment]
多分、画像を探すくんも同じ仕様だと思われます。そしてブックマーク時本来の名前を変えないと煩わしくなるのも一緒でしょう。ブックマーク時どういう名前を推奨しますか?

**Comment by enloyable** [comment]
あ、WWAの画像探すくんはブックマーク名そのままでも大丈夫でした

**Comment by enloyable** [comment]
Chromeの場合、
ブックマークする→編集→URLに魔法の呪文をコピーしてブックマーク名をアレにする→アレを検索して古いWWAで開く
これくらいの説明は必要かな

**Comment by enloyable** [comment]
あ、こっち閉めます？

**Comment by matsuyuki-a** [comment]
そうですね、wwawing.com 側にissueができたので、閉じます！
ご報告ありがとうございました！

**Comment by matsuyuki-a** [comment]
こちらの件対応しました。
スマートフォンの場合が若干不親切かもしれないですが、一旦ここまで 🙇
