### ISSUE TITLE
【スタンダードマップ】マップをブラウザで確認する方法の書き方の改善

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#132]
https://github.com/WWAWing/WWAWing/pull/109#issuecomment-496127804

**Comment by enloyable** [comment]
イシュー感謝します。許可関係どうしましょう？

**Comment by enloyable** [comment]
plicyさんについては圧縮についても書いたほうが良さそうですか？

**Comment by enloyable** [comment]
このマップをブラウザで見るには、同梱の「wwa-server.exe」をご利用ください。
〈p〉
「wwa-server.exe」を起動したまま、別のブラウザで
http://localhost:3000/マップ名.htmlと入力すると、ローカルでマップの仕上がりを確認できます。


例: http://localhost:3000/wwamap.html

〈p〉
また、firefoxやplicyでは「wwa-server.exe」を利用しなくても確認することができます。
〈p〉
plicyではzipに圧縮するソフトを使い、WWAゲームを、zipごとplicyのサーバーにアップロードする必要があります。

**Comment by enloyable** [comment]
少しセルフ文面改良。

**Comment by enloyable** [comment]
あ、大事なこと。もしこうすると、マップ作成ツールが3.18かそうでないかで書き方を大きく変えないといけません！3.18ならfirefoxしか☓だし（javasprict）3.19ならフェニックスの説明必要だし！

**Comment by enloyable** [comment]
なんとなく伝わってほしいけど、どうします？

**Comment by enloyable** [comment]
とりあえず現段階ではplicyの説明だけにします！？

**Comment by matsuyuki-a** [comment]
マップ作成ツールについては、WWA公式の3.10に統一することになったので、その方向で記述します。
(Wing Team で改良した作成ツールについては、同梱を行わない方針になりました)

**Comment by enloyable** [comment]
3.18以外だと旧javaでhtml出力するため、firefoxでもそのままでは☓なはずです

**Comment by enloyable** [comment]
このマップをブラウザで見るには、同梱の「wwa-server.exe」をご利用ください。
〈p〉
「wwa-server.exe」を起動したまま、別のブラウザで
http://localhost:3000/マップ名.htmlと入力すると、ローカルでマップの仕上がりを確認できます。

例: http://localhost:3000/wwamap.html

〈p〉
また、plicyでは「wwa-server.exe」を利用しなくても確認することができます。
〈p〉
plicyではzipに圧縮するソフトを使い、WWAゲームを、zipごとplicyのサーバーにアップロードする必要があります。

**Comment by enloyable** [comment]
plicyのみ残したセルフ文面です。ですが、将来的に改良した作成ツールを同梱する場合は、文面も改良しないといけませんね。
そのときはまたイシューお願いします。

**Comment by enloyable** [comment]
一旦その話は将来にするとして…フェニックスのことは載せます？

**Comment by matsuyuki-a** [comment]
Phoenixを使った方法については、推奨の方法ではない（Phoenixが更新終了となったこともあります）ので、載せない方向で調整したいです。

**Comment by matsuyuki-a** [comment]
ただし、Phoenixを使う方法が便利だとはこちらも認知しているので、何らかの代替案が出せるようにはしたいところです。

**Comment by enloyable** [comment]
3.10だと、htmlがjavaで出力されるので、フェニックスかwwaserverになりますけど…

**Comment by enloyable** [comment]
その話も将来でしょうね。作成ツールにplicyの名前を載せる場合、plicyさんに許可もらう必要あるかな…

**Comment by enloyable** [comment]
シャイんさんにstandardmapにplicyの名前を載せていいかdmします。もしだめなら今回は諦めます。

**Comment by matsuyuki-a** [comment]
DMじゃなくても普通に #request でよさそう

**Comment by enloyable** [comment]
このマップをブラウザで見るには、同梱の「wwa-server.exe」をご利用ください。
〈p〉
「wwa-server.exe」を起動したまま、別のブラウザで
http://localhost:3000/マップ名.htmlと入力すると、ローカルでマップの仕上がりを確認できます。

例: http://localhost:3000/wwamap.html

（実はplicyとfirefoxが絡まない部分も改良してました、やや気づきにくいかもだけど）

**Comment by enloyable** [comment]
シャイんさんの返答を待ちますね

**Comment by enloyable** [comment]
シャイんさんからplicyの説明載せるのを許可されました！

このマップをブラウザで見るには、同梱の「wwa-server.exe」をご利用ください。
〈p〉
「wwa-server.exe」を起動したまま、別のブラウザで
http://localhost:3000/マップ名.htmlと入力すると、ローカルでマップの仕上がりを確認できます。

例: http://localhost:3000/wwamap.html

〈p〉
また、plicyでは「wwa-server.exe」を利用しなくても確認することができます。
〈p〉
plicyではzipに圧縮するソフトを使い、WWAゲームを、zipごとplicyのサーバーにアップロードする必要があります。

現段階ではこの説明でよさそうなので閉じてください。ただし3.18にするときは、また別イシュー建ててくださいね。

**Comment by enloyable** [comment]
あ、締めてくださいじゃない…私はスマホだし色々あって今編集できないんだった…物体46の編集頼みます！

**Comment by enloyable** [comment]
（時折大切なことを忘れてしまい申し訳ない）

**Comment by enloyable** [comment]
（ちなみにわたしはホームページにupする際、htmlをノートで開いて、そこに他のhtmlをコピーして、その部分のマップ名だけ毎回変えてるけど、流石にそれは専門的な知識が要ると思う）

**Comment by enloyable** [comment]
wwa作者さんにplicyさんの利用が多いという理由で3.3より後回しにはしません。3.3入れたら本当に締めていいです。ただしfirefoxの件もあるのでこのイシューは締めても見れるようにしといてほしいです

**Comment by enloyable** [comment]
（あと、自分もそちらもややこしくなるので文面関連はfirefoxと確定したの以外消した）

**Comment by matsuyuki-a** [comment]
ちょっと話が長くなってきたので一旦closeとします。
