### ISSUE TITLE
短時間でわかるシリーズ同梱

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#133]
スタンダードマップを改良してて感じたことだけど、短時間でわかるシリーズ同梱しません？今後も色々と増やすかもですが。
https://plicy.net/GamePlay/74640
https://plicy.net/GamePlay/74804

**Comment by enloyable** [comment]
これ自体も改良を重ねないといけない部分があるのは承知ですので、私自身で時折改良してあげていきます。gidhubへの上げ方は分からないのでdiscordにあげます

**Comment by enloyable** [comment]
wwaが短時間で理解できることのメリットは遊ぶ側も作る側もメリットが大きいと考えます

**Comment by enloyable** [comment]
私が皆様を忙しくしてるのは重々承知しておりますが、これに関しては忙しさ故の必要性だと感じております…

**Comment by enloyable** [comment]
でも、私が抱えてる他の案件に比べると急ぐ必要はないのです

**Comment by enloyable** [comment]
割と小さめのバージョンアップのときに頼もう。今回は大きすぎるから見送り

**Comment by matsuyuki-a** [comment]
v3.4.0以降、対応します。
内容については一旦こちら側で精査させてください。

**Comment by enloyable** [comment]
（内容に関しては必要に応じて時々アップデートするつもりです）

**Comment by enloyable** [comment]
（ただ、口調やバージョンの反映などは考えますが、「1時間で作る」に関しては、バグってる世界が指示に従うと元に戻るというコンセプトですので、そこはご了承ください）

**Comment by matsuyuki-a** [comment]
短時間でわかるWWAマップもほしいけど、それ以上にちゃんとしたドキュメントがほしいなぁ...

**Comment by matsuyuki-a** [comment]
ドキュメントを整備したのでclose
