### ISSUE TITLE
一定時間無操作でプレイヤーが回るようにしたい

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#136]
Java版にあった(はず)の一定時間無操作でプレイヤーが回る(ジャンプゲートやゲーム開始時になるやつ)挙動を復活させる

ゲームスピードが50FPSじゃなくなったので、回る速さも再検討したい

**Comment by aokashi** [comment]
今回の Issue は #104 の件ではなく
- ジャンプゲートかゲーム開始直後でなくても、操作が無ければ入るようにする
- 動作速度を遅くする

ところがメインでしょうか？

**Comment by matsuyuki-a** [comment]
ですね
#104 は単純なバグだったのですが、今回の要望は、機能の不足・改善です

**Comment by enloyable** [comment]
…discordにも書いたのですが、乗り物酔いを考慮する必要性があります。回転速度を無闇に上げることには反対します。むしろ、下げてほしいと主張したいくらいなのです…

**Comment by matsuyuki-a** [comment]
もし変えるとするなら、速さを下方修正することになると思います。回転の1周期とフレーム数を見ながら調整していきます。

**Comment by enloyable** [comment]
私も乗り物酔いしやすく、回転で目を回しやすいので、割と切実です

**Comment by enloyable** [comment]
discordで反対派が多いので、回転までの間隔と速度を下げる方向性でいきません？（皆様のお気遣いに感謝します）

**Comment by enloyable** [comment]
一旦ここ閉めます？ある意味ほぼ真逆の提案ですので…

**Comment by enloyable** [comment]
#137立てましたー

**Comment by aokashi** [comment]
しばらくこの Issue はクローズします。
また必要になったら再度 Open に戻します。
