### ISSUE TITLE
プレイヤー追尾属性を3.02以前の弱い版と3.10以降の強い版から選べるようにする

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#139]
すっかり忘れてそうだけど…、
5月1日の。
「作成ツール的に
逃げる(弱い) と逃げる(強い)
プレーヤー追尾(弱い)とプレーヤー追尾(強い)があってもいいのかな」
って話があったので入れたいですね。でも今回やること多すぎなので次回のアップデートに回してもいいかも。

**Comment by enloyable** [comment]
![6BF0C010-37FE-4962-8764-0357ED47757E](https://user-images.githubusercontent.com/50323486/59144400-50bb3000-8a12-11e9-95c0-1f0b14317948.png)
本当に忘れてそうなので貼る

**Comment by matsuyuki-a** [comment]
ありがとうございます！

**Comment by enloyable** [comment]
http://phpjavascriptroom.com/?t=ajax&p=jquery_attributes_value
今までと違い、ほぼ自信ない。けど、調べた…

**Comment by matsuyuki-a** [comment]
作成ツールを改善する必要があるため、WWAMakerができてからになりそうです。

**Comment by enloyable** [comment]
了解です

**Comment by matsuyuki-a** [comment]
タイトルを具体的に書き直しました

**Comment by aokashi** [comment]
## 草案
- マクロは `$oldmove=0/1`
    - 由来は `$oldmap` から
- `1` と設定するとプレイヤー追尾と逃げるを 3.02 以前の挙動に変更
- `0` と設定するとプレイヤー追尾と逃げるを 3.10 以降の挙動に変更
