### ISSUE TITLE
中断セーブ機能

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#140]
私はsave.jsで対応しますが、だからといってパスワードが長すぎて、スマホだと取りづらい問題はなくなりませんね。パスワードを短くしたいな。これも今回の3.3は諦める。未来のお話。

**Comment by enloyable** [comment]
（ごめんなさい、こっちに関しては少しも役に立つことは調べられなさそうです…）

**Comment by matsuyuki-a** [comment]
PLiCyさん側で、差分セーブに関する実装が進んでいるようです。
実現すればかなり短くなると思います。

**Comment by matsuyuki-a** [comment]
v3.3.0 リリース → PLiCyさん取り込み →逆輸入
というフローを辿りそうです

**Comment by enloyable** [comment]
（見た目通りの1万文字の理由だけでなく、コピペの手間がスマホだとマウスに比べて大きいっていうのもある）

**Comment by enloyable** [comment]
ソース見てプリシーさんがやろうとしてることを理解しました。中断セーブ機能ですね。文言かえます？

**Comment by enloyable** [comment]
というわけでplicyさんがやろうとしてることを理解しましたので文言変えました

**Comment by matsuyuki-a** [comment]
PLiCy版の取り込み #201 で解決しそうなので、 単品のIssueとしてはクローズします。
