### ISSUE TITLE
プレイ時間をセーブデータに含める

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#149]
WWAData下にプレイ時間を含めたい
playingTime的なフィールドをつくり、セーブ時に `Date.now() - ロードorリスタート時刻` を 値に加算するとかすればできそう

**Comment by shine-star** [comment]
色々とごちゃごちゃしてしまっておりますが、PLiCyの方でプレイ時間格納の実装を致しました。

WWA Dataに変数が増えているので、ちょっと面倒ではありますが。
https://github.com/shine-star/WWAWing/blob/master/packages/common-interface/src/wwa_data.ts#L91

**Comment by matsuyuki-a** [comment]
PLiCyさんの方で、フレーム数ベースのプレイ時間格納が実装されたため、こちらのIssueは閉じようと思います。
