### ISSUE TITLE
$imgframe でアイテムボックスの枠画像を変更後、アイテムを取得すると、デフォルトの枠画像が表示されてしまう

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#155]
## 発生手順
1. `$imgframe` マクロでアイテムボックスの枠画像を変更する (Standard Map の物体パーツ197)
2. 適当なアイテムを取得する (Standard Map の物体パーツ113や107)
  - ただし、 `$effitem` マクロでアイテムエフェクトを無効にしていないことを前提とする

## 原因
アイテムエフェクトの表示先に適用されるCSSの `background-position` の値が固定値になっていると推測される。

## 環境
- OS: Windows 10 64bit
- ブラウザ: Firefox 69.0.3
- WWA Wingのバージョン: v3.2.1

## スクリーンショット
![WWAWing_321_VisibleDefaultItemBoxWithItemEffect](https://user-images.githubusercontent.com/12381375/67160809-7af10700-f38f-11e9-86c3-f230a882113e.png)

**Comment by matsuyuki-a** [comment]
なるほど...

**Comment by matsuyuki-a** [comment]
hotfixでいきますか～

**Comment by matsuyuki-a** [comment]
アイテムボックスの背景色、QuickSaveで保存されない仕様なのはWWA本家からの仕様だけど、使いにくいから保存されるようにしたほうがいいよな～

**Comment by matsuyuki-a** [comment]
どうせ直すならそういう仕様にした方がいいけれど、それをパッチリリースとして出すのはちょっと違う気がする。
Java版との互換切った以上は、こういうところも改善していかないとな～

**Comment by matsuyuki-a** [comment]
だけどバグはバグなので、直します
（一旦QuickSaveでは保存されない仕様のままで）
