### ISSUE TITLE
QuickSaveで保存されない$imgframeによるスタイル変更を、保存するようにする

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#156]
## 目的
v3.1系では、Java版との互換のために諦めていた、マクロ指定で書き換えられるスタイル情報（`$imgframe`) をQuickSaveデータに保存するようにする

v3.2系では、Java版との互換は考えなくてよいため、作業可能になった。

**Comment by aokashi** [comment]
今実装を進めているんですが、フレーム画像と操作パネルの各背景、ステータスの各アイコンの規定のイメージ座標が、 engine の WWAConsts には含まれているけど loader の WWAConsts には含まれていない状態になっています。
もしかしたら共通化を進めたほうが良さそうなので、共通化できないか模索してみます。

**Comment by matsuyuki-a** [comment]
loaderに入っていないのは、loaderで使わないからのはず
共通化は進めたいけれど、loaderでしか使わない定数とengineでしか使わない定数があってもいいかな～という気持ちです
