### ISSUE TITLE
効果音が一部分でしか再生されない

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#16]
再生される効果音がフルサイズ分再生されず、一部分でしか再生されない不具合があるようです。

例えばWWAデフォルトのクリック音である「カチッ」が「スッ」と聞こえます([ゲートワールド](http://wwajp.com/wwa/wwa.html))。
- WWA Wing W3.15a(W3.15でも確認済み)
- OS: Windows 10 Home
- Browser: Mozilla Firefox 47.0.1
  - Google Chrome 52系では問題なく再生されます

**Comment by aokashi** [comment]
まだ検証が不完全のため、同じWindows 10 or Firefoxでも同様の現象が発生しない場合があります。

**Comment by matsuyuki-a** [comment]
音源差し替え + WebAudio化によって解消されているはずなのでcloseします
