### ISSUE TITLE
imgframe のフレーム画像が変更されていない

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#194]
`$imgframe` マクロでフレーム画像を変更しても、 WWA Wing では変更が反映されていません。

## 発生手順
1. WWA Wingを起動し、物体パーツに197に触れる (`$imgframe=6,0,14`)

![wwa_wing-imgframe_not_change_frame](https://user-images.githubusercontent.com/12381375/76615960-6263d200-6566-11ea-99ff-5107f4b98415.png)

### Java版の実行結果
![wwa-imgframe_executed](https://user-images.githubusercontent.com/12381375/76615971-668fef80-6566-11ea-807f-e3a18823915c.png)

## 原因
WWA メインのインスタンスでは、フレーム画像が変更されているものの、描画を担当している CGManager にはその変更が行き届いていない可能性があります。

## 環境
- OS: Windows 10 (1903) 64bit と macOS Mojave 10.14.6
- ブラウザ: いずれも Firefox 74.0
- WWA Wingのバージョン: いずれも v3.2.11
  - ちなみに WWA Phoenix では正常に動作しています。

**Comment by aokashi** [comment]
#156 と併せて修正しようかな

**Comment by shine-star** [comment]
すみません、これ、軽量化のためにフレームをcanvasにキャッシュするようにしたのですが、そのキャッシュを更新する処理を付けていなかったのが原因かもしれません。

**Comment by shine-star** [comment]
直接毎フレームゲーム画面に32*32のフレームを描画する処理を、最初にフレーム全体を描画したcanvasを作成して、一回のdrawImageで描画できる仕組みに変えたのですが、その時の抜けだと思います。

**Comment by shine-star** [comment]
https://github.com/WWAWing/WWAWing/blob/develop/packages/engine/src/wwa_cgmanager.ts#L73
この_frameCanvas が原因です

**Comment by aokashi** [comment]
ご報告ありがとうございます。
`_frameCanvas` の更新が必要になりますね。

フレーム画像の変更と同時に、フレーム画像のキャッシュを更新するように修正してみます。
