### ISSUE TITLE
マイナーバージョンアップ 3.2.0

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#20]
WWA Wing では、 WWA Ver 3.10(2009年)以来となるマイナーバージョンアップを計画しています。

## WWA作成ツール 改め "WWA Wing 作成ツール"
- [ ]  現時点での @aokashi による成果を取り入れる。
- [ ]  部分的なWWA Wing対応。
- [ ] Visual Studio 2015以降でビルドが通らない問題の修正
- [ ] マップデータのバージョンを「3.2」に変更。
- [ ] PNG対応。「GIF画像」となっている箇所の文言修正。( ただし、アルファチャネルつきPNGは未対応とする。 )
- [ ]  BMP画像への対応の取りやめ

## WWA Wing
- [x] ビルド方式の大幅な見直し (v3.1.6) (#47)
  - [x] npm package化
  - [x] npm scripts によるビルド自動化
  - [x] TypeScript, uglify の npm パッケージ導入
  - [x] Travis CIによる`master` がコミットされた時の 「コンパイル」「minify」「配布バージョン作成」「push」までの完全自動化 (現在は配布バージョン作成以降のみが自動化されている。)
  - [x] 上記に合わせて、成果物の JS ファイルを `.gitignore` に追加
  -  [x] monorepo化。WWALoaderを取り込む 
- [ ] WWA Phoenixの別リポジトリ化。以降、WWA Phoenixは互換を重視するアップデートに、WWA Wingは新機能を重視するアップデートに移行。
  - [  もしかしたら、WWA Phoenixは「WWA Wing 後方互換版」になるかも...?

## WWA Wing公式サイト
- [x] 各最新版ダウンロードリンクを各リポジトリの「latest」に設定し、省力化。
- [x] WWA Wingの最新バージョン名の自動書き込み
- [x] 旧版ダウンロードリンクはGitHubの「Releases」ページへのリンクに変更。ただし、リポジトリ分割前のバージョンは別ページで個別対応。

**Comment by aokashi** [comment]
3,2,0 のバージョンアップが終わったため、クローズします。
