### ISSUE TITLE
ゼロ除算 (WWA Wing XE)

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#21]
@hirarira 
@90c42a7 で追加されたユーザ変数の割り算を行う関数  「`setUserValDiv` 」(マクロ `$var_div` )には、ゼロ除算を行ってしまうことがあります。0で割った場合には代入先の変数に `NaN` が代入されてしまうようです。
ユーザ変数は小数点代入を許可しない場合は「整数」とのことでしたので、 ご検討いただければと思います。
よろしくお願いします。

**Comment by matsuyuki-a** [comment]
WWA Wing XE がv3.3.0で入ることが確定したため、v3.3.0のマイルストーンを追加します

**Comment by hirarira** [comment]
長らく放置してしまいましたが、対応します

**Comment by matsuyuki-a** [comment]
お、であれば次にように対応してください。
1. xe-migration-2 ブランチから、新しいブランチを切る
2. 修正をコミットする
3. PRを xe-migration2 ブランチ向けにつくり、 @matsuyuki-a のレビューを受ける
4. 修正を xe-migration2 ブランチにマージする

**Comment by matsuyuki-a** [comment]
xe-migration-2 ブランチは、 v3.2.0にWWAWingXE 相当の機能を追加した ブランチです。
develop 向けのPRが #92 にあります

**Comment by hirarira** [comment]
ちなみにゼロ除算時の挙動はNaNが入るのが正しいような気がしますが…0を代入するのもおかしいですし

**Comment by matsuyuki-a** [comment]
これどうなんですかねー
NaNが入るのが仕様ということにしても大丈夫かもしれない
（マニュアルに、数値の演算については JavaScript (ECMA-262) に準拠します 的なことを書いて)

**Comment by hirarira** [comment]
NaNを入れるか、あるいはマクロ文自体を無効としてなんの挙動もさせないかどっちかな気がしますね

**Comment by matsuyuki-a** [comment]
`this._wwaData.userVar[x] = Math.floor(this._wwaData.userVar[x] / this._wwaData.userVar[y]);`

コードみた感じだと、今は整数値になるのが仕様か
0 で割ると NaN になります的な

**Comment by matsuyuki-a** [comment]
ただ、条件分岐マクロでのNaNの取扱をしっかりしないといけなくて
例えば、 NaN === NaN は false なので、
isNaN を使って NaNを検知する必要がありそうです。

**Comment by matsuyuki-a** [comment]
そうすると、NaNを認めること自体がちょっとわかりにくいなーと思うので、
マクロを無効にしてしまった方が早そうです

**Comment by shine-star** [comment]
0除算はツクール2000は0、ウディタは割られる数の値になりますね

**Comment by shine-star** [comment]
そういえばNaNやInfinityはJSONにするとnullになりますよ

**Comment by matsuyuki-a** [comment]
NaN が残っていると jump_rec_pos でフリーズしてしまうので徹底的に潰す必要がある

**Comment by matsuyuki-a** [comment]
- 各変数の最小値・最大値の決定
- 除算の結果が整数で収まらない場合（実数値をとる）ケースをどうするか
- 万が一 NaN や null, Infinity が発生した場合はどうするか

**Comment by hirarira** [comment]
安全に扱うためには以下のようにするのはどうでしょう？
 * ゼロ除算→結果をゼロにする or 計算前の値にする
 * 絶対値で `Number.MAX_SAFE_INTEGER` を超えた場合→結果をゼロにする or `Number.MAX_SAFE_INTEGER` に固定にする or 計算する前の値のままにする

**Comment by hirarira** [comment]
> 除算の結果が整数で収まらない場合（実数値をとる）ケースをどうするか

この場合は四捨五入 or 切り捨てでしょうかねえ

> 万が一 NaN や null, Infinity が発生した場合はどうするか

NaNとnull、undefinedが発生した場合には0を格納する、Inifinityもしくは `Number.MAX_SAFE_INTEGER`  を超過した場合には `Number.MAX_SAFE_INTEGER` に固定する？

**Comment by hirarira** [comment]
変数の最大値について候補
* 65000
  * WWAのパスワードセーブが保証する最大の数
  * 少し大きな数を作ろうとすると簡単に到達してしまうので避けたい
* 2147483648
  * `2^31`
  * ステータス欄に収まるギリギリ当たりの数
* `Number.MAX_SAFE_INTEGER`
  *  `2^53-1` = `9007199254740991`
  * 安全に扱える最大の整数
* `Number.MAX_VALUE`
  * `2^1024` = `1.79E+308`
  * 安全な整数の計算が行えない

**Comment by aokashi** [comment]
https://github.com/WWAWing/WWAWing/pull/378 より、ゼロ除算は結果が `0` になる仕様で実装を調整

**Comment by matsuyuki-a** [comment]
変数の最大値は `2^31-1`, 最小値は `-2^31` としようと思います。

根拠: ステータス欄に収まるから。 

なお、WWA Wing のパスワードセーブであれば 65000以上も保証されるので、Java版のパスワードセーブの基準はもう考えなくてよさそうだと思います。

**Comment by matsuyuki-a** [comment]
変数の上限・下限を突破した場合は、カンストとしようと思います。

**Comment by matsuyuki-a** [comment]
#390 で変数に関する仕様をまとめることになったため、単体の Issue としては close します。
今後、ゼロ除算の仕様について議論したい場合はあちらでお願いします。

**Comment by matsuyuki-a** [comment]
変数の最大値は、ミリ秒単位のタイムスタンプが代入できなくなってしまうことから、 やっぱり、`Number.MAX_SAFE_INTEGER` にすることにします。ただし、ステータスは表示できなくなってしまうので 2^31-1とします。 #390 にも反映済です。
