### ISSUE TITLE
WWAのパスワードデータのコピーボタンの検討

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#275]
パスワードデータのコピー画面では、コピーとペーストのショートカットキーが表記されていますが、 Windows や Linux 以外ではこの表記は役に立たないことや、マウスクリックでコピーできる手段が存在していることから、コピーボタンの実装が出来るのではないかと思います。

クリップボードへのコピーについては、 IE 対応を除けば簡単な実装で済みますが、 IE への対応が必要になると特殊な処理を埋め込む必要がありそうです。

**Comment by matsuyuki-a** [comment]
IE対応が切れたら実装でOK

**Comment by aokashi** [comment]
もしくは、 IE の場合はボタンそのものを非表示にしてしまう方法もあり

**Comment by matsuyuki-a** [comment]
クリップボードAPIが使えないIE11では document.execCommand を使うのもありかもしれない
WWA Phoenix の実装例
https://github.com/WWAPhoenix/wwaphoenix.github.io/pull/3

**Comment by matsuyuki-a** [comment]
ゲームデバイスなどでは塞いだ方がいいかも

**Comment by matsuyuki-a** [comment]
IEがなくなったので対応可能
