### ISSUE TITLE
data-wwa-autosave=0 が効かない？

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#295]
https://jbbs.shitaraba.net/bbs/read.cgi/netgame/14732/1430319317/98

## 発生手順
(以下のような手順を書く。)
1. 物体パーツに〇〇を設定する
2. WWA Wingを起動し、物体パーツに触れる

## 原因
(もし原因がわかれば、説明する。ただし、WWA Wing内部に詳しい人でないと分からないので無理して書く必要は無い。)

## 環境
(各項目すべて埋めるようにする。)
- OS: [Windows 10 64bit]
- ブラウザ: [Firefox 64]
- WWA Wingのバージョン: [v3.1.6]

(また、スクリーンショットも加えることも推奨する)

**Comment by aokashi** [comment]
Standard Map で `data-wwa-autosave` を `0` に付与した状態で試しましたが、200歩目でオートセーブされています。

**Comment by aokashi** [comment]
原因多分分かった気がする。

オートセーブの歩数設定では、 WWA Wing 起動時に `WWASaveDataLogList` の `setAutoInterval` メソッドが実行されるのですが、与えられた引数である `autoInterval` では 0 以下ではクラス内で処理する変数 `_autoInterval` には代入されません。

代入されないままどうなるのかといいますと、 `WWASaveDataLogList` クラス生成時の規定値 `200` がそのまま使用されます。
なので、 `setAutoInterval` の条件分岐だけ外すことで機能するのではないかと思います。

**Comment by matsuyuki-a** [comment]
お、修正までお願いしてもいいですか？:pray:
