### ISSUE TITLE
Java 版原作と挙動をそろえるオプションの検討

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#300]
## 目的
WWA Wing は v3.2.0 以降から Java 版原作との挙動をそろえない方向で開発を進めていましたが、その後 Java 版で動作していた作品が WWA Wing では正常に動作しないバグがいくつか発見しました (#267)。

今更 WWA Wing v3.1.x の開発を再開するのも手間がかかるので、現在の WWA Wing とは明らかに動作が異なるような挙動について再現したい場合、どのようにしてオプションを用意するか、そしてどのように実装するか検討することになりました。

## 現時点で分かっていること
下記の2つの方法があります。

### WWA Wing の挙動を揃える `data-wwa-java-compatible` オプションを新設
オプションの指定方法については、1つ1つの挙動の文字列をカンマ区切りで複数指定します。例えば #267 については `zero-floor` とし、 `data-wwa-java-compatible="zero-floor"` という風に指定します。

`all` とした場合は、 WWA Wing で用意した Java 版の挙動をすべて再現できます。

### `data-wwa-classic-mode-enable` オプションに Java 版原作と挙動を揃えるようにしておく
1つ1つの挙動再現はせず、 `true` とした場合は Java 版の挙動すべてを再現します。

見た目だけクラシックモードにしたい場合は向きませんが、オプションの数が少なくなるので説明書が簡潔に済ませられたり、ゲーム作成の問題発生時に解決する手段が少なくなって悩む時間が減ったりするメリットはあります。

**Comment by matsuyuki-a** [comment]
#267 のように、ゲーム自体に関する挙動は、 $oldmap や $default などのマクロで進めていきたいです。
data-属性で指定するものは、なるべくゲームの挙動に関わらない設定であるのが望ましいと考えます。
（Issueは一旦closeしようと思いますが、異論大歓迎なので、なにかありましたらコメントください 🙇 )
