### ISSUE TITLE
IE11 でセーブデータが残らない

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#301]
#299 で IE11 の動作確認をしたところ、セーブデータが残らない不具合が見つかり、 WWA Wing v3.5.3 でも確認したところ同様に再現されましたのでご報告します。

## 発生手順
1. WWA Wing を起動し、適当な場所に Quick Save する
2. リロードしたり IE を再起動したりして再度 `1.` でアクセスしたページに再度アクセスする
3. コンソールに `DOM7011: このページのコードによって、バックワード キャッシュとフォワード キャッシュが無効になりました。詳細については、http://go.microsoft.com/fwlink/?LinkID=291337 を参照してください。` が表示される
4. Quick Save したセーブデータが残っておらず、 Quick Load となるべきボタンが Password になっていることを確認

## 原因
現時点で不明ですが、「インターネット オプション」の閲覧の履歴の設定から表示される「Web サイトデータの設定」からは「キャッシュおよびデータベース」に WWA Wing のページのドメインが残っているため、 Quick Save のデータ自体はセーブされていると思います。

前述の発生手順に表示されているメッセージを考えると、 IE11 の設定による問題もあるかもしれません。

## 環境
- OS: Windows 10 64bit 2004
- ブラウザ: Internet Explorer 11.572.19041.0
- WWA Wingのバージョン: v3.5.3
    - v3.5.1 PLiCy Edition でも同様に再現できました

**Comment by matsuyuki-a** [comment]
どちらかというと、パスワードが残らない、というよりは「IndexedDBへの保存に失敗する」に近い模様

IndexedDBに保存 (put) しようとすると、[ここのtry-catch](https://github.com/WWAWing/WWAWing/blob/051ca8faa40a293033210100a90e86c040b8719a/packages/engine/src/wwa_save/WWASaveDataDBList.ts#L147)にハマってしまう (エラー内容: DataError)

変数に保存されているQuickSaveデータは読めているので、ページから離れない限りはセーブデータは読み出せる

**Comment by matsuyuki-a** [comment]
keypathを配列ではなく、1つだけ与えるようにして、そのIDを URL + セーブ位置 (0,1,2,3)で生成するようにすれば保存できるようになった

ただし、以前のDBと互換性がなくなってしまうため、マイグレーション処理を書く必要がある。

読み出しも現在の getAlEmulate だと cursor が null を返してきてうまく動かないので、もし対応させるなら、 get を使って書き直す必要がある。

**Comment by matsuyuki-a** [comment]
既存コードのデグレリスク、マイグレーション処理を永遠に保守し続けることを考えたら、いっそのことIEはIE専用処理にしてしまった方がよさそうなので、その方向で進める。

IEが専用コードになると、Edgeレガシのサポートが終了するとgetAllのエミュレート処理を消すことができる

**Comment by shine-star** [comment]
確かそれ、頑張って対応しようとしたけどIE11独自の互換性バグっぽいのがあって対応力を諦めたんです

**Comment by matsuyuki-a** [comment]
互換性バグというと、どんな具合でしょうか？
IE11の中でも読めたり読めなかったりする環境があるとかなら諦めようと思います.

**Comment by shine-star** [comment]
確か格納できる変数に違いがあったり、Chromeと同じ記述をしても保存してくれなかったりしたので…
当時のEDGEでは通っていたので何か不自然な挙動で、対応するのを諦めました

**Comment by matsuyuki-a** [comment]
なので、もしIE対応させるなら専用のコードにしようかなぁと思ってます。
格納できる変数に違いがあるのはちょっと慎重にかくにしてみます。
無理だと確信したら諦めます

**Comment by matsuyuki-a** [comment]
情報ありがとうございました 🙇
