### ISSUE TITLE
oldmove の解説キャラクターを Standard Map に追加

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#305]
#303 が終わりました。
`$oldmove` マクロの解説を行うパーツを Standard Map に追加します。

### どこに置くべきか？
WWA Wing で追加された部分はオレンジ色の背景で差別化されているので、 Java 版からすでにあった箇所に追加してもよさそうです。

ただし、追尾アルゴリズムの確認を行うスペースを設ける必要があると思いますが、そうなると遠い場所に置かなくてはなりません。遠い場所になるとマップの順路を見て回るには違和感がありすぎるので、一工夫必要になると思います。

**Comment by aokashi** [comment]
`X=50~60 Y=40~50` かその横が適切かな？

**Comment by matsuyuki-a** [comment]
例えば、解説する人はこれまでのように、解説している道の途中のどこかに置いて、話しかけるか、近くのジャンプゲートを踏むと、test.dat みたいな空間に飛ばされるとか

**Comment by matsuyuki-a** [comment]
> `X=50~60 Y=40~50` かその横が適切かな？

よさそう、自分のさきほどのコメントは、(X,Y)=(53,48)に解説する人を設置して、話しかけるか、近くのジャンプゲートを踏むと、test.dat みたいな空間に飛ばされるのを想像してました！

**Comment by aokashi** [comment]
空間的にも余裕があるのでわざわざジャンプゲートで別の空間に飛ばす必要もなさそうです。

**Comment by matsuyuki-a** [comment]
よさそう
