### ISSUE TITLE
WWA Wing XE 機能統合

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#368]
`xe-migration-2` ブランチを `develop` ブランチに統合するにあたってのタスクリストです

- [x] 追加されるマクロの一覧を書き出す → [既にヒラ氏がまとめてくれていた](https://github.com/hirarira/WWAWingXE/wiki/%E5%AE%9F%E8%A3%85%E6%B8%88%E3%83%9E%E3%82%AF%E3%83%AD)
- [x] ゼロ除算の対応 https://github.com/WWAWing/WWAWing/issues/21
- [x] パーツを書き換える処理のIDTable対応
- [x] 現段階のWWA Wing で採用できないマクロの廃止・現行に合わせるための仕様変更
- [x] QuickSave永続化対応 (変数など、追加されるセーブデータについての対応)
- [x] オートセーブ対応
- [x] 変数ダンプHTMLの統合
- [x] マニュアルに `data-wwa-var-dump-elm` 属性について追記
- [x] スタンダードマップ拡張 #378 
- [x] 機能差分の確認: https://github.com/WWAWing/WWAWing/pull/59 と変わらないこと
- [x] テストプレイ (NAOさんの作品, Continueあたり)

**Comment by aokashi** [comment]
📝 持ち物がいっぱいかどうかを判別できる機能を実装できるようにしたい
