### ISSUE TITLE
WWA Wing XE 機能統合: 変数の仕様についてまとめるIssue

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#390]
WWA Wing XE の変数の仕様について、議論や決定した事柄が分散してしまっているので、このIssueにまとめることにします。

既に個別に立っているIssueは close させていただきます。

マニュアル: https://wwawing.notion.site/7-5a4b3d475684414683242ded9fd57694

**Comment by matsuyuki-a** [comment]
## 変数に関する仕様
- 変数の数は 256個
- 変数の番号(添字)は 0 から 255 まで
- 整数のみを保持できる
- 最大値は `2^31-1`
- 最小値は `-2^31`
- 除算の結果は、整数部分のみとなる
- 計算結果が最大値より大きくなる場合は、計算結果を最大値とする。
- 計算結果が最小値より小さくなる場合は、計算結果を最小値とする。
- 0 で割る演算があった場合は、結果を 0 とする

**Comment by shine-star** [comment]
互換性を保ちつつ、可読性を高める提案です

テキスト全体に、下記のような置換処理を挟むことはできないでしょうか？
```
"$v[50]+=$v[13]".replace(/^\$v\[(\d+)\]\+=\$v\[(\d+)\]$/,"$var_add=$1,$2")
"$v[50]*=$v[13]".replace(/^\$v\[(\d+)\]\*=\$v\[(\d+)\]$/,"$var_mul=$1,$2")
"$v[50]=$at".replace(/^\$v\[(\d+)\]\=\$at$/,"$copy_at_to=$1")

```

また、XEの実装はいつごろできそうかもお教えいただければ助かります

**Comment by matsuyuki-a** [comment]
マニュアルに変数の仕様がまとまることになったので、本件はcloseします。
ステータス値の上限がない問題については別件で管理します。
