### ISSUE TITLE
中断セーブ機能

### ISSUE THREAD

**Issue by hirarira** [WWAWing/WWAWing#516]
## 発生手順、目的
通常のオートセーブとは別に任意のタイミングで中断できるセーブ機能を設ける
目的としては基本的にはセーブ禁止のWWAにて、任意のタイミングにて離席できるようにしておきたい
機能としては再度WWAを開いた際には中断セーブは削除されるような仕様としたい

**Comment by matsuyuki-a** [comment]
おっと、既出ですね #227 
こちらはcloseします。
