### ISSUE TITLE
マップデータをブラウザで見るの書き換え

### ISSUE THREAD

**Issue by enloyable** [WWAWing/WWAWing#517]
(このIssueに関する簡単に説明)
マップデータをブラウザで見る機能を使えばhtmlが生成されるが、このhtmlはjava版のもので書き換えが必要
(不具合であれば https://github.com/WWAWing/WWAWing/issues/new?template=bug.md から作成することを推奨)

## 発生手順、目的
書き換えの手間を省く

## 実行手順
WWAWINGのマップデータをブラウザで見るを、JavaScript版のものにする

**Comment by matsuyuki-a** [comment]
お、これは [WWAMaker](https://github.com/WWAWing/WWAMaker) ですね、そちらの方で開発が進んでます！
WWAWing としては close します。
