### ISSUE TITLE
BGM の開始を遅延させる方法の提案

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#593]
## 発生手順、目的
BGM の切り替わりが突然発生するのはゲーム体験上良くない事がある。
（自分の作品の「謎めいた機械を追い求めて」では、コイズミ市街地でのBGMの切り替わりに違和感を覚えるかもしれない）

街に入ってBGMが入るまで1テンポ遅らせれば多少違和感を軽減することが可能になると思う。

## 設計構造
`$audiodelay` マクロを検討中。

- 引数は遅延させる秒（ミリ秒単位）
- 設定すると70番以降のBGMがすべて指定したミリ秒遅延させてから再生する
- ループ再生の遅延は含まれない（1ループ終わった次のループの以降は遅延なく発生させる）
- 実行しない場合は従来どおり遅延なくBGMを再生させる
- 名前の `audio` は効果音と混合するため、 `$bgmdelay` などの名前も考えている

**Comment by matsuyuki-a** [comment]
既存マクロは　$sound なので、 `$sounddelay` がいいかな
単発で遅延させるための $sound の第2引数設定もよさそう

**Comment by aokashi** [comment]
#608 で実装したのでこの Issue は Close します。
