### ISSUE TITLE
テーマCSSをつくる

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#71]
wwa_classic.css は、wwa.css の代替として現在存在しているが、コードとしてwwa.cssと多くの重複を抱えている。これは、メンテナンスの観点からあまり好ましいものとは言えない。

そこで、WWAとして最小限必要なもののみを wwa.css に残し、その上でユーザ定義のテーマを別ファイルのCSSとして表現することにより、コードの重複をなくすことを考えたい。
wwa.cssの定義を上書きすることもできるようにしたい。

**Comment by aokashi** [comment]
- 実際に配布される際にはwwa.cssとwwa_classic.cssの2つになる
- ソースコードは基本CSSとテーマ用のCSS(sass|scss)がある
  - 配布時にはこれらのCSSファイルをビルドする

という形にしたいですが、🆗？

**Comment by aokashi** [comment]
WWA Wingの内部パッケージ styles を追加し、そこにSCSSファイルを配置。ビルドできるようにします。

WWA Wingの基本CSSは core ディレクトリに配置し、各部位ごとに分割します。分割したCSSをまとめる役割としてcoreディレクトリに `core.scss` を配置します。

クラシックモードのように、追加のカスタマイズが必要な場合は extends ディレクトリに配置します。

ビルドすると、coreディレクトリ内の `core.scss` と、ソースコード内で指定したextendsディレクトリのSCSSファイルからCSSファイルが複数出来上がります。

# 懸念事項
- `z-index.scss` を追加して、重ね管理できるようにしたい。
- CSSライブラリが追加できるように vendor ディレクトリとか modules ディレクトリを追加したい。

**Comment by aokashi** [comment]
上記をディレクトリ構造に表すと、こうなる？

```
styles
|-src ... ソースファイル
| |-core ... 基本SCSSファイル群
| | |- _*.scss ... 各部位のSCSSファイル
| | |- _z-index.scss ... 階層管理
| | `- core.scss ... 上記SCSSファイルをまとめたファイル
| |-exntends ... 追加で上書きするSCSSファイル群
| | `-* ... テーマ別にディレクトリを作る
| |   |- _*.scss ... 追加で必要な場合は入れる。
| |   `- core.scss ... テーマをコンパイルする場合はこのSCSSファイルから。
| `- *.ts ... ビルド用ソースファイル
|-lib ... ビルド用ファイル
`-output ... SCSSビルドで生成したCSSファイル群
```
srcディレクトリにSCSSファイルとTypeScriptファイルが混在しているところが心配だったりします。わざわざTypeScriptにしなくてもlibファイルにJSそのままでも良さそう？

**Comment by aokashi** [comment]
TODO
- [ ] `lerna init` でテーマCSSが自動でビルドされるようにする(もしくはできるか検証する)
- [ ] CSSのビルドからデバッグサーバーへの適用を行うタスクコマンドをWWAWingの `package.json` に追加する
- [ ] (時間があれば) z-index の適用CSSを、要素のクラス名からなる配列から参照するようにする

**Comment by matsuyuki-a** [comment]
終わってそうなので閉じます。
問題あれば再度開けてください 🙇
