### ISSUE TITLE
Battle Report ボタンをGo to WWAに変更できるようにする

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#72]
PLiCy導入分をマージしたことに伴い、右下の Go to WWA が Battle Report に変更されました。

`data-***` 属性の指定などで変更できるようにします。

もしかしたらバーチャルパッドを実装したほうが早そう・・・？

**Comment by matsuyuki-a** [comment]
v3.2.0 現在では、 `data-wwa-use-go-to-wwa`  属性でいきます
その後のバージョンでどうするかは、相談させてください

**Comment by matsuyuki-a** [comment]
v3.2.0時点で実現したため、closeします。
今後新しくGo to WWAをユーザに選ばさせるような実装を作る場合は別issueを立ててください。（or立てます)
