### ISSUE TITLE
ステータス変化パーツでステータス不足が起こるとそのパーツが残る

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAWing#8]
ステータス変化のパーツで特定のステータスをマイナス指定にすると、そのステータスが減少します。不足すると何も起こらず、そのパーツは消去されます。

ただし、WWA Wingだと消去されずに残ってしまうようです。

# 例
1. Standard Mapの初期防御力を0に設定
2. X27 Y46にある防御力を減らす扉に触れる
3. X45 Y39の$statusマクロに話しかけて防御力を補充する
4. 2.で触れた扉に行くとその手前のパーツが反応し、扉が消える(普通は扉に触れると反応する)

# 利用環境
* OS:Microsoft Windows 10 Home 64bit
* ブラウザ:Mozilla Firefox 43.0.4
* WWA Wing W3.14b+(**例**では、WWA Phoenixを介して実行)

# 対策
* 扉の2つ以上前(1マス以上離れたところ)にステータス変化のパーツを消去する処理を加える
  * 指定位置にパーツを出現ウインドウや$partsマクロで設定する
  * 道パーツが効果的

**Comment by rmn31415** [comment]
うおお、マジだ！！対応させていただきます。。。

**Comment by rmn31415** [comment]
当該バグの詳細な解析が完了したので報告します。

バグの実際は、スタンダードマップ(X, Y)=(27, 46)の扉のように、
攻撃力・防御力・所持金ステータスが負になるようなステータス変化のパーツがプレイヤーの上に乗ってイベントが実行された時に、次のフレームでもキーおよびマウスの入力が継続して有効となるという問題でした。

スタンダードマップでは、物体番号131（扉）の指定位置パーツ出現により、プレイヤー座標に物体番号132を出現させます。132番はステータス変化なので、ステータスが規定量ない場合にはイベントが実行されません。ですので、この状態で上キーが押しっぱなし（もしくは、マウス操作継続）だと、すぐ上のパーツ番号131が再び反応し、再度プレイヤー座標に物体パーツ132を配置させます。

WWA Wingの仕様上、再度同じ座標に出現したパーツ132は実行されないため、プレイヤーがこの位置から残ると物体パーツ132が残ってしまいます。

本来なら、ステータス不足時のプレイヤー座標に存在するステータス変化は、イベントが実行されず消滅するのですが、スタンダードマップの場合は上に扉があるという特殊な配置のため、このような結果になったと思われます。

次のバージョンでは、ステータス変化が実行されず消滅する場合は、キー入力とマウス入力の状態を一旦クリアし、プレイヤー進行方向のイベントを実行させないようにします。

ご報告ありがとうございました。

**Comment by rmn31415** [comment]
というわけで、 7106837 にて修正させていただきましたー、リリースをお楽しみにー

**Comment by rmn31415** [comment]
バージョン W3.15　にて修正させていただきました。
Thanks!
