### ISSUE TITLE
効果音データの音声ファイルが見つからないとエラーメッセージなしで止まる

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/WWAWing#80]
タイトル通り。
AudioJSを廃止するときになんとかする

**Comment by aokashi** [comment]
:memo:
音声ファイルが見つからない場合のフリーズは `checkAllSoundLoaded` で止まっている。
(WebAudioの場合)

**Comment by aokashi** [comment]
📝 
IEの場合は、 `requestAnimationFrame(soundCheckCaller)` で止まった
(ソースコードを部分的に変えている関係で違った動作になるかもしれない)

**Comment by enloyable** [comment]
https://kuroeveryday.blogspot.com/2018/03/frame-skip-in-requestanimationframe.html?m=1
キーワードで調べたけど有用そう
